apiVersion: v1
kind: Pod
metadata:
  name: kafka-3
  labels:
    app: kafka-3
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-server:5.4.0
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "2000Mi"
    env:
    - name: KAFKA_BROKER_ID
      value: "3"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka-3:9092
    - name: CONFLUENT_METRICS_ENABLE
      value: 'false'
    - name: KAFKA_INTER_BROKER_PROTOCOL_VERSION
      value: "2.0"
    - name: KAFKA_LOG_MESSAGE_FORMAT_VERSION 
      value: "2.0"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
spec:
  selector:
    app: kafka-3
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-4
  labels:
    app: kafka-4
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-server:5.4.0
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "2000Mi"
    env:
    - name: KAFKA_BROKER_ID
      value: "4"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka-4:9092
    - name: CONFLUENT_METRICS_ENABLE
      value: 'false'
    - name: KAFKA_INTER_BROKER_PROTOCOL_VERSION
      value: "2.0"
    - name: KAFKA_LOG_MESSAGE_FORMAT_VERSION 
      value: "2.0"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-4
spec:
  selector:
    app: kafka-4
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-5
  labels:
    app: kafka-5
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-server:5.4.0
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "2000Mi"
    env:
    - name: KAFKA_BROKER_ID
      value: "5"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka-5:9092
    - name: CONFLUENT_METRICS_ENABLE
      value: 'false'
    - name: KAFKA_INTER_BROKER_PROTOCOL_VERSION
      value: "2.0"
    - name: KAFKA_LOG_MESSAGE_FORMAT_VERSION 
      value: "2.0"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-5
spec:
  selector:
    app: kafka-5
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
