apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: default
spec:
  containers:
  - name: zookeeper
    image: confluentinc/cp-zookeeper:5.4.0
    resources:
      limits:
        memory: "1000Mi"
      requests:
        memory: "1000Mi"
    env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181

---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-0
  namespace: default
  labels:
    app: kafka-0
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-kafka:5.4.0
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "2000Mi"
    env:
    - name: KAFKA_BROKER_ID
      value: "0"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka-0:9092
    - name: CONFLUENT_METRICS_ENABLE
      value: 'false'

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0
spec:
  selector:
    app: kafka-0
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-1
  namespace: default
  labels:
    app: kafka-1
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-kafka:5.4.0
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "2000Mi"
    env:
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka-1:9092
    - name: CONFLUENT_METRICS_ENABLE
      value: 'false'

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  selector:
    app: kafka-1
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-2
  namespace: default
  labels:
    app: kafka-2
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-kafka:5.4.0
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "2000Mi"
    env:
    - name: KAFKA_BROKER_ID
      value: "2"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka-2:9092
    - name: CONFLUENT_METRICS_ENABLE
      value: 'false'

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
spec:
  selector:
    app: kafka-2
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
